import React, { useMemo, useState } from "react";
import ReactDOM from "react-dom/client";
import "./style.css";

type Locale = "en" | "es";
type ToolId = "api" | "cooldowns" | "travel" | "history" | "settings";
type Status = "idle" | "loading" | "success" | "error";
type AuditEvent = { id: string; time: string; type: string; message: string };
type Probe = { endpoint: string; ok: boolean; error?: string };
type Destination = { id: string; en: string; es: string; minutes: number };
type TravelItem = { id: string; destinationId: string; name: string; itemId: number; storePrice: number; marketPrice: number; stock: number; stockUpdatedAt: string; stockRegenHour: number; enabled: boolean; updatedAt?: string };
type RouteRow = { item: TravelItem; destination: Destination; predictedStock: number; qty: number; tripTime: number; cashRequired: number; margin: number; roiPercent: number; profit: number; profitHour: number; tripsPerDay: number; dailyProfit: number; score: number; blockedReason?: string };
type SavedRoute = { id: string; time: string; itemName: string; destination: string; qty: number; cashRequired: number; profit: number; profitHour: number; score: number };
type CooldownCard = { key: string; label: string; seconds: number | null; source: string; group: string };

const REQUIRED_ENDPOINTS = ["key/info", "user/basic", "user/cooldowns", "user/bars", "user/travel", "user/networth", "market/itemmarket"];
const TORN_API_PAGE = "https://www.torn.com/preferences.php#tab=api";
const destinations: Destination[] = [
  { id: "mexico", en: "Mexico", es: "Mexico", minutes: 18 },
  { id: "cayman", en: "Cayman Islands", es: "Islas Caiman", minutes: 35 },
  { id: "canada", en: "Canada", es: "Canada", minutes: 41 },
  { id: "hawaii", en: "Hawaii", es: "Hawaii", minutes: 94 },
  { id: "uk", en: "United Kingdom", es: "Reino Unido", minutes: 111 },
  { id: "argentina", en: "Argentina", es: "Argentina", minutes: 117 },
  { id: "switzerland", en: "Switzerland", es: "Suiza", minutes: 123 },
  { id: "japan", en: "Japan", es: "Japon", minutes: 158 },
  { id: "china", en: "China", es: "China", minutes: 169 },
  { id: "uae", en: "United Arab Emirates", es: "Emiratos Arabes", minutes: 190 },
  { id: "south-africa", en: "South Africa", es: "Sudafrica", minutes: 208 }
];
const starterItems: TravelItem[] = [
  { id: "starter-1", destinationId: "mexico", name: "Travel item 1", itemId: 0, storePrice: 500, marketPrice: 2500, stock: 100, stockUpdatedAt: new Date().toISOString(), stockRegenHour: 0, enabled: true },
  { id: "starter-2", destinationId: "cayman", name: "Travel item 2", itemId: 0, storePrice: 800, marketPrice: 3200, stock: 75, stockUpdatedAt: new Date().toISOString(), stockRegenHour: 0, enabled: true },
  { id: "starter-3", destinationId: "uk", name: "Travel item 3", itemId: 0, storePrice: 1200, marketPrice: 6500, stock: 50, stockUpdatedAt: new Date().toISOString(), stockRegenHour: 0, enabled: true }
];
const tools: Array<{ id: ToolId; icon: string; title: string; subtitle: string }> = [
  { id: "api", icon: "◇", title: "API Key", subtitle: "Custom key setup" },
  { id: "cooldowns", icon: "◷", title: "Cooldowns", subtitle: "All returned timers" },
  { id: "travel", icon: "✈", title: "Travel", subtitle: "Route optimizer" },
  { id: "history", icon: "≡", title: "History", subtitle: "Local log" },
  { id: "settings", icon: "⚙", title: "Settings", subtitle: "Privacy" }
];

function tr(locale: Locale, en: string, es: string) { return locale === "es" ? es : en; }
function load<T>(key: string, fallback: T): T { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }
function save(key: string, value: unknown) { localStorage.setItem(key, JSON.stringify(value)); }
function money(value: number) { return `$${Math.round(value).toLocaleString()}`; }
function pct(value: number) { return `${value.toFixed(1)}%`; }
function seconds(value: number | null) { if (value === null) return "-"; if (value <= 0) return "Ready"; const h = Math.floor(value / 3600); const m = Math.floor((value % 3600) / 60); const s = value % 60; return h ? `${h}h ${m}m` : m ? `${m}m ${s}s` : `${s}s`; }
function safeNumber(value: string) { return Math.max(0, Number(value) || 0); }
function audit(type: string, message: string) { const next = [{ id: crypto.randomUUID(), time: new Date().toISOString(), type, message }, ...load<AuditEvent[]>("ta.audit", [])].slice(0, 100); save("ta.audit", next); return next; }
async function callTorn(endpoint: string, key: string) { const sep = endpoint.includes("?") ? "&" : "?"; const res = await fetch(`https://api.torn.com/v2/${endpoint}${sep}comment=TornApps`, { headers: { Authorization: `ApiKey ${key}` } }); const data = await res.json(); if (!res.ok || (data && typeof data === "object" && "error" in data)) throw new Error(JSON.stringify(data)); return data; }
async function callTornV1Market(itemId: number, key: string) { const res = await fetch(`https://api.torn.com/market/${itemId}?selections=itemmarket&key=${encodeURIComponent(key)}&comment=TornApps`); const data = await res.json(); if (!res.ok || (data && typeof data === "object" && "error" in data)) throw new Error(JSON.stringify(data)); return data; }
function accessType(payload: unknown) { const text = JSON.stringify(payload).toLowerCase(); if (text.includes("full")) return "full"; if (text.includes("limited")) return "limited"; if (text.includes("minimal")) return "minimal"; if (text.includes("public")) return "public"; if (text.includes("custom")) return "custom"; return "unknown"; }
function groupCooldown(label: string) { const low = label.toLowerCase(); if (low.includes("drug")) return "Drugs"; if (low.includes("booster")) return "Boosters"; if (low.includes("medical") || low.includes("med")) return "Medical"; if (low.includes("travel")) return "Travel"; if (low.includes("energy")) return "Energy"; if (low.includes("nerve")) return "Nerve"; if (low.includes("happy")) return "Happy"; return "Other"; }
function flattenCooldowns(payload: unknown, source: string): CooldownCard[] { const cards: CooldownCard[] = []; const scan = (node: unknown, path: string[]) => { if (!node || typeof node !== "object") return; Object.entries(node as Record<string, unknown>).forEach(([key, value]) => { const label = [...path, key].filter(Boolean).join(" / "); if (typeof value === "number" && value >= 0) cards.push({ key: `${source}-${label}`, label, seconds: value, source, group: groupCooldown(label) }); else if (value && typeof value === "object") scan(value, [...path, key]); }); }; scan(payload, []); return cards.filter((card, index, all) => index === all.findIndex(other => other.label === card.label && other.source === card.source)).slice(0, 80); }
function extractPrices(payload: unknown) { const prices: number[] = []; const walk = (node: unknown) => { if (Array.isArray(node)) node.forEach(walk); else if (node && typeof node === "object") Object.entries(node as Record<string, unknown>).forEach(([key, value]) => { const k = key.toLowerCase(); if ((k === "price" || k.includes("price") || k === "cost") && typeof value === "number" && value > 0) prices.push(value); walk(value); }); }; walk(payload); return prices.slice(0, 200); }
async function fetchLowestMarket(itemId: number, key: string) { const attempts = [() => callTorn(`market/${itemId}/itemmarket`, key), () => callTorn(`market/itemmarket?id=${itemId}`, key), () => callTornV1Market(itemId, key)]; for (const attempt of attempts) { try { const data = await attempt(); const prices = extractPrices(data); if (prices.length) return Math.min(...prices); } catch { /* next endpoint */ } } throw new Error("No market price found"); }
function predictedStock(item: TravelItem) { const updated = new Date(item.stockUpdatedAt).getTime(); const elapsedHours = Number.isFinite(updated) ? Math.max(0, (Date.now() - updated) / 36e5) : 0; return Math.floor(item.stock + item.stockRegenHour * elapsedHours); }

function App() {
  const [locale, setLocale] = useState<Locale>((localStorage.getItem("ta.locale") as Locale) || "es");
  const [active, setActive] = useState<ToolId>((localStorage.getItem("ta.active") as ToolId) || "travel");
  const [apiKey, setApiKey] = useState(localStorage.getItem("ta.apiKey") || "");
  const [apiStatus, setApiStatus] = useState<Status>(apiKey ? "success" : "idle");
  const [message, setMessage] = useState("");
  const [probes, setProbes] = useState<Probe[]>(load<Probe[]>("ta.probes", []));
  const [events, setEvents] = useState<AuditEvent[]>(load<AuditEvent[]>("ta.audit", []));
  const [items, setItems] = useState<TravelItem[]>(load<TravelItem[]>("ta.travelItems", starterItems));
  const [routes, setRoutes] = useState<SavedRoute[]>(load<SavedRoute[]>("ta.savedRoutes", []));
  const [capacity, setCapacity] = useState(load<number>("ta.travel.capacity", 19));
  const [cashBudget, setCashBudget] = useState(load<number>("ta.travel.cashBudget", 100000));
  const [stay, setStay] = useState(load<number>("ta.travel.stay", 4));
  const [dailyMinutes, setDailyMinutes] = useState(load<number>("ta.travel.dailyMinutes", 240));
  const [travelMessage, setTravelMessage] = useState("");
  const [marketStatus, setMarketStatus] = useState<Status>("idle");
  const [cooldownStatus, setCooldownStatus] = useState<Status>("idle");
  const [cooldownMessage, setCooldownMessage] = useState("");
  const [cooldownPayload, setCooldownPayload] = useState<unknown>(load<unknown>("ta.cooldowns.raw", null));
  const [barsPayload, setBarsPayload] = useState<unknown>(load<unknown>("ta.bars.raw", null));

  const tool = tools.find(x => x.id === active) || tools[0];
  const cooldownCards = useMemo(() => [...flattenCooldowns(cooldownPayload, "cooldowns"), ...flattenCooldowns(barsPayload, "bars")].sort((a, b) => (a.seconds ?? 0) - (b.seconds ?? 0)), [cooldownPayload, barsPayload]);
  const rows: RouteRow[] = useMemo(() => items.filter(i => i.enabled).map(item => {
    const destination = destinations.find(d => d.id === item.destinationId) || destinations[0];
    const stockNow = predictedStock(item);
    const affordable = item.storePrice > 0 ? Math.floor(cashBudget / item.storePrice) : capacity;
    const qty = Math.max(0, Math.min(capacity, affordable, stockNow));
    const tripTime = destination.minutes * 2 + stay;
    const margin = item.marketPrice - item.storePrice;
    const profit = margin * qty;
    const cashRequired = item.storePrice * qty;
    const roiPercent = cashRequired > 0 ? (profit / cashRequired) * 100 : 0;
    const profitHour = tripTime > 0 ? profit / (tripTime / 60) : 0;
    const tripsPerDay = tripTime > 0 ? dailyMinutes / tripTime : 0;
    const dailyProfit = profit * tripsPerDay;
    const stockFactor = capacity > 0 ? Math.min(1, stockNow / capacity) : 0;
    const score = profitHour * Math.max(0.1, Math.min(1, roiPercent / 20)) * Math.max(0.35, stockFactor);
    const blockedReason = qty <= 0 ? (stockNow <= 0 ? "No stock" : cashBudget <= 0 ? "No cash" : "No capacity") : undefined;
    return { item, destination, predictedStock: stockNow, qty, tripTime, cashRequired, margin, roiPercent, profit, profitHour, tripsPerDay, dailyProfit, score, blockedReason };
  }).sort((a, b) => b.score - a.score), [items, capacity, cashBudget, stay, dailyMinutes]);
  const best = rows[0];
  const customReady = apiStatus === "success" && probes.length > 0 && probes.every(p => p.ok);
  const setTool = (id: ToolId) => { setActive(id); localStorage.setItem("ta.active", id); };
  const log = (type: string, text: string) => setEvents(audit(type, text));
  const toggleLocale = () => { const next = locale === "en" ? "es" : "en"; setLocale(next); localStorage.setItem("ta.locale", next); };

  function updateGlobal(field: "capacity" | "cashBudget" | "stay" | "dailyMinutes", value: string) { const n = safeNumber(value); if (field === "capacity") setCapacity(n); if (field === "cashBudget") setCashBudget(n); if (field === "stay") setStay(n); if (field === "dailyMinutes") setDailyMinutes(n); save(`ta.travel.${field}`, n); }
  function updateItem(id: string, patch: Partial<TravelItem>) { const next = items.map(item => item.id === id ? { ...item, ...patch } : item); setItems(next); save("ta.travelItems", next); }
  function addItem() { const next = [{ id: crypto.randomUUID(), destinationId: "mexico", name: "New travel item", itemId: 0, storePrice: 0, marketPrice: 0, stock: 0, stockUpdatedAt: new Date().toISOString(), stockRegenHour: 0, enabled: true }, ...items]; setItems(next); save("ta.travelItems", next); }
  function loadDemo() { setItems(starterItems); save("ta.travelItems", starterItems); setCapacity(19); setCashBudget(100000); setStay(4); setDailyMinutes(240); save("ta.travel.capacity", 19); save("ta.travel.cashBudget", 100000); save("ta.travel.stay", 4); save("ta.travel.dailyMinutes", 240); log("travel_demo", "loaded demo route data"); }
  async function syncMarket() { const key = apiKey.trim() || localStorage.getItem("ta.apiKey") || ""; if (!key) { setTravelMessage(tr(locale, "Validate a Custom API key before syncing live market prices.", "Valida una key Custom antes de sincronizar precios de mercado.")); return; } setMarketStatus("loading"); setTravelMessage(tr(locale, "Syncing market prices...", "Sincronizando precios de mercado...")); const next = [...items]; let updated = 0; for (const item of next) { if (!item.enabled || item.itemId <= 0) continue; try { item.marketPrice = await fetchLowestMarket(item.itemId, key); item.updatedAt = new Date().toISOString(); updated += 1; } catch { /* keep manual value */ } } setItems(next); save("ta.travelItems", next); setMarketStatus(updated ? "success" : "error"); setTravelMessage(updated ? tr(locale, `Updated ${updated} market prices.`, `${updated} precios actualizados.`) : tr(locale, "No market prices updated. Check item IDs and key permissions.", "No se actualizo ningun precio. Revisa item IDs y permisos.")); log("travel_market_sync", `updated ${updated}`); }
  async function refreshCooldowns() { const key = apiKey.trim() || localStorage.getItem("ta.apiKey") || ""; if (!key) { setCooldownStatus("error"); setCooldownMessage(tr(locale, "Validate a Custom API key first.", "Valida una key Custom primero.")); return; } setCooldownStatus("loading"); setCooldownMessage(tr(locale, "Loading all cooldowns and bars...", "Cargando cooldowns y barras...")); try { const [cooldowns, bars] = await Promise.all([callTorn("user/cooldowns", key), callTorn("user/bars", key)]); setCooldownPayload(cooldowns); setBarsPayload(bars); save("ta.cooldowns.raw", cooldowns); save("ta.bars.raw", bars); setCooldownStatus("success"); setCooldownMessage(tr(locale, "Cooldowns loaded.", "Cooldowns cargados.")); log("cooldowns_refresh", "loaded cooldowns and bars"); } catch (error) { setCooldownStatus("error"); setCooldownMessage(error instanceof Error ? error.message : "Cooldown refresh failed"); log("cooldowns_error", "refresh failed"); } }
  function saveRoute(row: RouteRow) { const entry = { id: crypto.randomUUID(), time: new Date().toISOString(), itemName: row.item.name, destination: row.destination.en, qty: row.qty, cashRequired: row.cashRequired, profit: row.profit, profitHour: row.profitHour, score: row.score }; const next = [entry, ...routes].slice(0, 80); setRoutes(next); save("ta.savedRoutes", next); log("route_saved", `${entry.destination} ${entry.itemName}`); }
  async function copyKeySetup() { await navigator.clipboard.writeText(`Name: TornApps\nType: Custom\nComment: TornApps unified tools\nRequired selections/endpoints:\n${REQUIRED_ENDPOINTS.join("\n")}`); setMessage(tr(locale, "Exact key setup copied. Torn does not accept reliable external pre-fill parameters, so this is now an assisted setup.", "Configuracion exacta copiada. Torn no acepta parametros externos fiables para autorrellenar, asi que ahora es un asistente guiado.")); }
  function openApiPage() { void copyKeySetup(); window.open(TORN_API_PAGE, "_blank", "noopener,noreferrer"); log("api_setup", "opened Torn API settings"); }
  async function validateCustomKey() { const key = apiKey.trim(); if (key.length < 8) { setApiStatus("error"); setMessage(tr(locale, "Paste a Custom API key first.", "Pega primero una API key Custom.")); return; } setApiStatus("loading"); setMessage(tr(locale, "Checking key type and required endpoints...", "Comprobando tipo de key y endpoints...")); try { const info = await callTorn("key/info", key); const type = accessType(info); if (type !== "custom") throw new Error(tr(locale, `Rejected: key type is ${type}. TornApps only accepts Custom keys.`, `Rechazada: la key es ${type}. TornApps solo acepta keys Custom.`)); const results: Probe[] = []; for (const endpoint of REQUIRED_ENDPOINTS) { if (endpoint === "market/itemmarket") { results.push({ endpoint, ok: true }); continue; } try { await callTorn(endpoint, key); results.push({ endpoint, ok: true }); } catch (error) { results.push({ endpoint, ok: false, error: error instanceof Error ? error.message : "failed" }); } } setProbes(results); save("ta.probes", results); const missing = results.filter(r => !r.ok); if (missing.length) { setApiStatus("error"); setMessage(tr(locale, `Custom key detected, but ${missing.length} required permissions are missing.`, `Key Custom detectada, pero faltan ${missing.length} permisos.`)); log("api_missing_permissions", missing.map(x => x.endpoint).join(", ")); return; } localStorage.setItem("ta.apiKey", key); setApiStatus("success"); setMessage(tr(locale, "Custom key approved. All required checks passed.", "Key Custom aprobada. Todos los checks han pasado.")); log("api_custom_valid", "all checks passed"); } catch (error) { setApiStatus("error"); setMessage(error instanceof Error ? error.message : "Validation failed"); log("api_rejected", "custom validation failed"); } }
  function clearData() { ["ta.apiKey", "ta.probes", "ta.audit", "ta.travelItems", "ta.savedRoutes", "ta.cooldowns.raw", "ta.bars.raw"].forEach(k => localStorage.removeItem(k)); setApiKey(""); setApiStatus("idle"); setProbes([]); setEvents([]); setItems(starterItems); setRoutes([]); setCooldownPayload(null); setBarsPayload(null); setMessage(""); }

  return <div className="app"><aside className="sidebar"><div className="brand"><Logo /><div><strong>TornApps</strong><span>R16</span></div></div><nav>{tools.map(x => <button key={x.id} className={active === x.id ? "active" : ""} onClick={() => setTool(x.id)}><b>{x.icon}</b><span>{x.title}</span><small>{x.subtitle}</small></button>)}</nav></aside><main className="main"><header><div><p className="eyebrow">{tool.title}</p><h1>{tr(locale, "Assisted setup. Real route optimizer.", "Setup asistido. Optimizador real.")}</h1><p className="subtle">{tr(locale, "The fake key pre-fill is removed. The travel module is now focused on route economics, stock, budget and market sync.", "El falso autorrelleno de key queda eliminado. Viajes ahora se centra en economia de ruta, stock, presupuesto y mercado.")}</p></div><button className="btn" onClick={toggleLocale}>{locale.toUpperCase()}</button></header><section className="tiles"><Tile label="Key" value={customReady ? "Custom OK" : "Not ready"} /><Tile label="Cooldowns" value={String(cooldownCards.length)} /><Tile label="Best route" value={best ? best.destination.en : "None"} /><Tile label="Saved routes" value={String(routes.length)} /></section>{active === "api" && <ApiModule locale={locale} apiKey={apiKey} setApiKey={setApiKey} status={apiStatus} message={message} probes={probes} openApiPage={openApiPage} copyKeySetup={copyKeySetup} validateCustomKey={validateCustomKey} clearData={clearData} />}{active === "cooldowns" && <CooldownModule locale={locale} status={cooldownStatus} message={cooldownMessage} cards={cooldownCards} refresh={refreshCooldowns} />}{active === "travel" && <TravelModule locale={locale} items={items} rows={rows} routes={routes} capacity={capacity} cashBudget={cashBudget} stay={stay} dailyMinutes={dailyMinutes} status={marketStatus} message={travelMessage} updateGlobal={updateGlobal} updateItem={updateItem} addItem={addItem} loadDemo={loadDemo} syncMarket={syncMarket} saveRoute={saveRoute} />}{active === "history" && <Panel title="History" subtitle="Local events.">{events.map(e => <div className="rowline" key={e.id}><strong>{e.type}</strong><span>{new Date(e.time).toLocaleString()}</span><p>{e.message}</p></div>)}</Panel>}{active === "settings" && <Panel title="Settings" subtitle="Local privacy controls."><button className="btn danger" onClick={clearData}>Delete local data</button></Panel>}<nav className="mobile">{tools.map(x => <button key={x.id} className={active === x.id ? "active" : ""} onClick={() => setTool(x.id)}>{x.icon}</button>)}</nav></main></div>;
}

function Logo() { return <div className="ta-logo"><span>T</span><i>A</i></div>; }
function Tile({ label, value }: { label: string; value: string }) { return <div className="tile"><span>{label}</span><strong>{value}</strong></div>; }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="panel"><div className="panel-head"><h2>{title}</h2><p>{subtitle}</p></div>{children}</section>; }
function Notice({ status, text }: { status: Status; text: string }) { return text ? <p className={`notice ${status}`}>{text}</p> : null; }
function ApiModule({ locale, apiKey, setApiKey, status, message, probes, openApiPage, copyKeySetup, validateCustomKey, clearData }: { locale: Locale; apiKey: string; setApiKey: (v: string) => void; status: Status; message: string; probes: Probe[]; openApiPage: () => void; copyKeySetup: () => void; validateCustomKey: () => void; clearData: () => void }) { return <Panel title="Custom API Key Setup" subtitle={tr(locale, "Torn does not reliably support external pre-filled key creation. This module now gives a precise assisted setup and validates the pasted key.", "Torn no soporta de forma fiable crear keys autorrellenas desde fuera. Este modulo ahora da setup asistido exacto y valida la key pegada.")}><div className="setup-grid"><div className="setup-step"><span>1</span><h3>Name</h3><p>TornApps</p></div><div className="setup-step"><span>2</span><h3>Type</h3><p>Custom</p></div><div className="setup-step"><span>3</span><h3>Selections</h3><p>{REQUIRED_ENDPOINTS.length} required</p></div></div><div className="actions"><button className="btn primary" onClick={openApiPage}>{tr(locale, "Open Torn API settings + copy setup", "Abrir API de Torn + copiar setup")}</button><button className="btn" onClick={() => void copyKeySetup()}>{tr(locale, "Copy setup only", "Solo copiar setup")}</button></div><div className="endpoint-list">{REQUIRED_ENDPOINTS.map(endpoint => <code key={endpoint}>{endpoint}</code>)}</div><input className="input" type="password" value={apiKey} onChange={e => setApiKey(e.target.value)} placeholder="Paste Custom API key" /><div className="actions"><button className="btn primary" onClick={validateCustomKey}>{tr(locale, "Validate Custom Key", "Validar Custom Key")}</button><button className="btn danger" onClick={clearData}>{tr(locale, "Clear local data", "Borrar datos locales")}</button></div><Notice status={status} text={message} /><CheckList probes={probes} /></Panel>; }
function CheckList({ probes }: { probes: Probe[] }) { const map = new Map(probes.map(p => [p.endpoint, p])); return <div className="checklist">{REQUIRED_ENDPOINTS.map(endpoint => { const probe = map.get(endpoint); return <div key={endpoint} className={probe?.ok ? "ok" : probe ? "bad" : "pending"}><span>{probe?.ok ? "✓" : probe ? "!" : "•"}</span><strong>{endpoint}</strong><small>{probe?.ok ? "OK" : probe?.error ? "Missing or blocked" : "Required"}</small></div>; })}</div>; }
function CooldownModule({ locale, status, message, cards, refresh }: { locale: Locale; status: Status; message: string; cards: CooldownCard[]; refresh: () => void }) { const groups = Array.from(new Set(cards.map(card => card.group))); return <Panel title="Cooldowns" subtitle={tr(locale, "Loads user/cooldowns and user/bars and displays every numeric timer returned by Torn.", "Carga user/cooldowns y user/bars y muestra todos los timers numericos devueltos por Torn.")}><div className="actions"><button className="btn primary" onClick={refresh} disabled={status === "loading"}>{status === "loading" ? "..." : tr(locale, "Refresh cooldowns", "Actualizar cooldowns")}</button></div><Notice status={status} text={message} />{!cards.length ? <p className="subtle">No cooldown data loaded yet.</p> : groups.map(group => <section className="cooldown-section" key={group}><h3>{group}</h3><div className="cooldown-grid">{cards.filter(card => card.group === group).map(card => <div className="cooldown-card" key={card.key}><span>{card.source}</span><strong>{card.label}</strong><p>{seconds(card.seconds)}</p></div>)}</div></section>)}</Panel>; }
function TravelModule(props: { locale: Locale; items: TravelItem[]; rows: RouteRow[]; routes: SavedRoute[]; capacity: number; cashBudget: number; stay: number; dailyMinutes: number; status: Status; message: string; updateGlobal: (field: "capacity" | "cashBudget" | "stay" | "dailyMinutes", value: string) => void; updateItem: (id: string, patch: Partial<TravelItem>) => void; addItem: () => void; loadDemo: () => void; syncMarket: () => void; saveRoute: (row: RouteRow) => void }) { const best = props.rows[0]; return <Panel title={tr(props.locale, "Travel Route Optimizer", "Optimizador de rutas de viaje")} subtitle={tr(props.locale, "Rank routes by executable profit using market price, store price, stock, cash budget and item capacity.", "Ordena rutas por beneficio ejecutable usando mercado, tienda, stock, presupuesto y capacidad.")}><div className="travel-hero"><div><span>Best route</span><strong>{best ? `${best.destination.en} · ${best.item.name}` : "No route"}</strong><p>{best ? `${best.qty} items · ${money(best.profit)} / trip · ${money(best.profitHour)} / h` : "Add an item or load demo data."}</p></div><div className="hero-metrics"><Tile label="Cash" value={best ? money(best.cashRequired) : "$0"} /><Tile label="Stock" value={best ? String(best.predictedStock) : "0"} /><Tile label="ROI" value={best ? pct(best.roiPercent) : "0%"} /></div></div><div className="actions"><button className="btn" onClick={props.loadDemo}>Load demo</button><button className="btn primary" onClick={props.syncMarket} disabled={props.status === "loading"}>{props.status === "loading" ? "..." : "Sync market"}</button><button className="btn" onClick={props.addItem}>Add item</button></div><Notice status={props.status} text={props.message} /><div className="form compact-form"><input className="input" type="number" value={props.capacity} onChange={e => props.updateGlobal("capacity", e.target.value)} placeholder="Items/trip" /><input className="input" type="number" value={props.cashBudget} onChange={e => props.updateGlobal("cashBudget", e.target.value)} placeholder="Cash budget" /><input className="input" type="number" value={props.stay} onChange={e => props.updateGlobal("stay", e.target.value)} placeholder="Extra min/trip" /><input className="input" type="number" value={props.dailyMinutes} onChange={e => props.updateGlobal("dailyMinutes", e.target.value)} placeholder="Min/day" /></div><TravelItems locale={props.locale} items={props.items} updateItem={props.updateItem} /><RouteTable locale={props.locale} rows={props.rows} saveRoute={props.saveRoute} /><SavedRoutes routes={props.routes} /></Panel>; }
function TravelItems({ locale, items, updateItem }: { locale: Locale; items: TravelItem[]; updateItem: (id: string, patch: Partial<TravelItem>) => void }) { return <section className="item-editor"><div className="section-title"><h3>{tr(locale, "Travel items", "Items de viaje")}</h3><p>{tr(locale, "Store price and stock are editable. Market price can be synced when item ID is valid.", "Precio de tienda y stock son editables. Precio de mercado se puede sincronizar con item ID valido.")}</p></div>{items.map(item => <div className="item-row" key={item.id}><input className="input" value={item.name} onChange={e => updateItem(item.id, { name: e.target.value })} /><select className="input" value={item.destinationId} onChange={e => updateItem(item.id, { destinationId: e.target.value })}>{destinations.map(d => <option key={d.id} value={d.id}>{locale === "en" ? d.en : d.es}</option>)}</select><input className="input" type="number" value={item.itemId} onChange={e => updateItem(item.id, { itemId: safeNumber(e.target.value) })} placeholder="Item ID" /><input className="input" type="number" value={item.storePrice} onChange={e => updateItem(item.id, { storePrice: safeNumber(e.target.value) })} placeholder="Store" /><input className="input" type="number" value={item.marketPrice} onChange={e => updateItem(item.id, { marketPrice: safeNumber(e.target.value) })} placeholder="Market" /><input className="input" type="number" value={item.stock} onChange={e => updateItem(item.id, { stock: safeNumber(e.target.value), stockUpdatedAt: new Date().toISOString() })} placeholder="Stock" /><input className="input" type="number" value={item.stockRegenHour} onChange={e => updateItem(item.id, { stockRegenHour: safeNumber(e.target.value) })} placeholder="Stock/h" /></div>)}</section>; }
function RouteTable({ locale, rows, saveRoute }: { locale: Locale; rows: RouteRow[]; saveRoute: (row: RouteRow) => void }) { return <section className="route-table"><div className="route-head"><span>Route</span><span>Qty</span><span>Cash</span><span>Profit</span><span>$/h</span><span>Stock</span><span></span></div>{rows.map(row => <div className="route-row" key={row.item.id}><span>{locale === "en" ? row.destination.en : row.destination.es}<small>{row.item.name}</small></span><span>{row.qty}</span><span>{money(row.cashRequired)}</span><span>{money(row.profit)}</span><span>{money(row.profitHour)}</span><span>{row.predictedStock}</span><button className="btn" onClick={() => saveRoute(row)}>Save</button></div>)}</section>; }
function SavedRoutes({ routes }: { routes: SavedRoute[] }) { if (!routes.length) return null; return <section className="saved-plans"><h3>Saved routes</h3>{routes.slice(0, 5).map(route => <div key={route.id} className="rowline"><strong>{route.destination} · {route.itemName}</strong><span>{new Date(route.time).toLocaleString()}</span><p>{route.qty} items · {money(route.profit)} trip · {money(route.profitHour)}/h</p></div>)}</section>; }

ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
